# SPDX-License-Identifier: Apache-2.0

[toolchain]
anchor_version = "0.29.0"
[workspace]
members = ["programs/refi-ipt"]

[features]
seeds = false
skip-lint = false

[programs.localnet]
refi_ipt = "HpPJBUex6FdSw7CGvYzjtUmM1629RNTqgCyu6pfcyNBx"

# [programs.devnet]
# refi_ipt = "HpPJBUex6FdSw7CGvYzjtUmM1629RNTqgCyu6pfcyNBx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 60000

[test.validator]
bind_address = "127.0.0.1"
rpc_port = 8899